name: Build and Analysis
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  sonarcloud:
    name: Build and analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - uses: actions/checkout@v4.2.2
          
      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        with:
          version: 9
          
      - name: Install Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Test and coverage
        run: pnpm run coverage
